### PR TITLE
version user_roles migration template

### PR DESCRIPTION
**Pull request by dunn**
Fixes GH-27.

### CODE REVIEW

**Comment by elrayle** [comment]
First off @dunn, thanks for working on this.

FYI... There was a discussion at a samvera-tech call to do the work of making this compatible with Rails 5 by adding the migration information.  I believe it was determined that there needed to be a new release of this gem when the fix is made.  This is because adding the version info on the migration makes the migration incompatible with Rails 4.  So we need a dividing line between the release that works with Rails 4 and the release that works with Rails 5.

See the minutes from the tech call for more information...  https://wiki.duraspace.org/x/tKM2BQ

**Comment by dunn** [comment]
Gotcha, @elrayle 

Is there a way to detect what version of Rails is running the generator? Then we could add the version only when necessary.

**Comment by elrayle** [comment]
In a rails app, I would use...
```
Rails::VERSION::STRING[0].to_i < 5
```

**Comment by dunn** [comment]
We can also do `Rails::VERSION::MAJOR`; updated the PR.

**Comment by elrayle** [comment]
Even better.

**Comment by dunn** [comment]
Is this good to merge then?

**Comment by mjgiarlo** [comment]
I defer to @elrayle. Thanks, @dunn!

**Pull request merged**
