### PR TITLE
Adding Ruby 2.7.z and Rails 6.y.z to the CircleCI build configuration

### PR DESCRIPTION
**Pull request by randalldfloyd**

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
I'm not certain why CircleCI isn't running for this, as the builds should be run for forked pull requests:
image

**Comment by jrgriffiniii** [comment]
These tests don't appear to be running on https://circleci.com/gh/randalldfloyd/hydra-role-management (or, they were 18 hours ago). Further, on the last commit, there were failing tests.

**Comment by jrgriffiniii** [comment]
CircleCI failed to trigger the build given some internal configuration issues, and this will be resolved.

**Comment by jrgriffiniii** [comment]
Regarding the RuboCop upgrade and removal of Bixby which I needed to undertake for my own updates, please see https://github.com/samvera/browse-everything/pull/317/commits/65c6c6a381b6727f84c0f56fa0451888669704b0 for reference.

**Comment by randalldfloyd** [comment]
@jrgriffiniii Finally got over all my onboarding and got a fully passing PR!

**Pull request merged**
