### PR TITLE
Integrates CircleCI for continuous integration

### LINKED ISSUE #44: Use CircleCI for continuous integration
Derived from samvera/maintenance#16

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #44

### CODE REVIEW

**Comment by tpendragon** [comment]
@jrgriffiniii Why the complicated workflow? Are we getting something from separating bundle/lint from everything else?

**Comment by cjcolvar** [comment]
Since this gem requires an engine cart generate and multiple ruby versions being tested, I think it makes sense to have a separate build (bundle, lint, generate) job from the test jobs.

**Comment by tpendragon** [comment]
Coveralls didn't report back. Did you add the COVERALLS_REPO_TOKEN to the CircleCI environment variables @jrgriffiniii ?

**Comment by jrgriffiniii** [comment]
Coveralls is now reporting for this.

**Pull request merged**
